<a href="https://colab.research.google.com/github/RRAJ644/Exploratory-Data-Analysis/blob/main/Exploratory_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import statistics

In [13]:
# Import Dataset

def importData():
  dataset=pd.read_csv('/Churn_Modelling.csv')
  return dataset

df = importData()

df.info()
# df.head()
# df.tail()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           9871 non-null   object
 6   Age              9887 non-null   float64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(3), int64(8), object(3)
memory usage: 1.1+ MB

In [14]:
print(df.isnull().sum())

RowNumber            0
CustomerId           0
Surname              0
CreditScore          0
Geography            0
Gender             129
Age                113
Tenure               0
Balance              0
NumOfProducts        0
HasCrCard            0
IsActiveMember       0
EstimatedSalary      0
Exited               0
dtype: int64

In [15]:
# Handling missing values - deleting the entire column
updatedDf = df.dropna(axis=1)
updatedDf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Tenure           10000 non-null  int64
 6   Balance          10000 non-null  float64
 7   NumOfProducts    10000 non-null  int64
 8   HasCrCard        10000 non-null  int64
 9   IsActiveMember   10000 non-null  int64
 10  EstimatedSalary  10000 non-null  float64
 11  Exited           10000 non-null  int64
dtypes: float64(2), int64(8), object(2)
memory usage: 937.6+ KB

In [16]:
# Delete rows with missing data
updatedDf = df.dropna(axis=0)
updatedDf.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9780 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        9780 non-null   int64
 1   CustomerId       9780 non-null   int64
 2   Surname          9780 non-null   object
 3   CreditScore      9780 non-null   int64
 4   Geography        9780 non-null   object
 5   Gender           9780 non-null   object
 6   Age              9780 non-null   float64
 7   Tenure           9780 non-null   int64
 8   Balance          9780 non-null   float64
 9   NumOfProducts    9780 non-null   int64
 10  HasCrCard        9780 non-null   int64
 11  IsActiveMember   9780 non-null   int64
 12  EstimatedSalary  9780 non-null   float64
 13  Exited           9780 non-null   int64
dtypes: float64(3), int64(8), object(3)
memory usage: 1.1+ MB

In [17]:
#fill missing values with imputation mean
updatedDf.loc[:, 'Age'] = updatedDf['Age'].fillna(df['Age'].mean())
print(updatedDf.info())

<class 'pandas.core.frame.DataFrame'>
Index: 9780 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        9780 non-null   int64
 1   CustomerId       9780 non-null   int64
 2   Surname          9780 non-null   object
 3   CreditScore      9780 non-null   int64
 4   Geography        9780 non-null   object
 5   Gender           9780 non-null   object
 6   Age              9780 non-null   float64
 7   Tenure           9780 non-null   int64
 8   Balance          9780 non-null   float64
 9   NumOfProducts    9780 non-null   int64
 10  HasCrCard        9780 non-null   int64
 11  IsActiveMember   9780 non-null   int64
 12  EstimatedSalary  9780 non-null   float64
 13  Exited           9780 non-null   int64
dtypes: float64(3), int64(8), object(3)
memory usage: 1.1+ MB
None

In [18]:
# Forward and Backward filling - Imputation

# bfill & ffill
updatedDf1 = updatedDf.copy()
updatedDf1['Age'] = updatedDf1['Age'].bfill()
updatedDf1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9780 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        9780 non-null   int64
 1   CustomerId       9780 non-null   int64
 2   Surname          9780 non-null   object
 3   CreditScore      9780 non-null   int64
 4   Geography        9780 non-null   object
 5   Gender           9780 non-null   object
 6   Age              9780 non-null   float64
 7   Tenure           9780 non-null   int64
 8   Balance          9780 non-null   float64
 9   NumOfProducts    9780 non-null   int64
 10  HasCrCard        9780 non-null   int64
 11  IsActiveMember   9780 non-null   int64
 12  EstimatedSalary  9780 non-null   float64
 13  Exited           9780 non-null   int64
dtypes: float64(3), int64(8), object(3)
memory usage: 1.1+ MB

In [19]:
df.describe().round(2)

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00,10000.00,10000.00,9887.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.0
mean,5000.50,15690940.57,650.53,38.93,5.01,76485.89,1.53,0.71,0.52,100090.24,0.2
std,2886.90,71936.19,96.65,10.50,2.89,62397.41,0.58,0.46,0.50,57510.49,0.4
min,1.00,15565701.00,350.00,18.00,0.00,0.00,1.00,0.00,0.00,11.58,0.0
25%,2500.75,15628528.25,584.00,32.00,3.00,0.00,1.00,0.00,0.00,51002.11,0.0
50%,5000.50,15690738.00,652.00,37.00,5.00,97198.54,1.00,1.00,1.00,100193.92,0.0
75%,7500.25,15753233.75,718.00,44.00,7.00,127644.24,2.00,1.00,1.00,149388.25,0.0
max,10000.00,15815690.00,850.00,92.00,10.00,250898.09,4.00,1.00,1.00,199992.48,1.0

In [20]:
# Feature scaling
# Standard Scaler & MinMaxScaler

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,NaN,2,125510.82,1,1,1,79084.10,0

In [21]:
df.describe().round(2)

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00,10000.00,10000.00,9887.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.0
mean,5000.50,15690940.57,650.53,38.93,5.01,76485.89,1.53,0.71,0.52,100090.24,0.2
std,2886.90,71936.19,96.65,10.50,2.89,62397.41,0.58,0.46,0.50,57510.49,0.4
min,1.00,15565701.00,350.00,18.00,0.00,0.00,1.00,0.00,0.00,11.58,0.0
25%,2500.75,15628528.25,584.00,32.00,3.00,0.00,1.00,0.00,0.00,51002.11,0.0
50%,5000.50,15690738.00,652.00,37.00,5.00,97198.54,1.00,1.00,1.00,100193.92,0.0
75%,7500.25,15753233.75,718.00,44.00,7.00,127644.24,2.00,1.00,1.00,149388.25,0.0
max,10000.00,15815690.00,850.00,92.00,10.00,250898.09,4.00,1.00,1.00,199992.48,1.0

In [29]:
newDataFrame = pd.DataFrame(df, columns=['Age', 'Tenure'])
newDataFrame.head()

    Age  Tenure
0  42.0       2
1  41.0       1
2  42.0       8
3  39.0       1
4   NaN       2

In [31]:
newDataFrame.loc[:, 'Age']=newDataFrame['Age'].fillna(newDataFrame['Age'].mean())
newDataFrame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Age     10000 non-null  float64
 1   Tenure  10000 non-null  int64
dtypes: float64(1), int64(1)
memory usage: 156.4 KB

In [32]:
# Normalization
scaler = MinMaxScaler()
normalizedDf = scaler.fit_transform(newDataFrame)
print(normalizedDf)

[[0.32432432 0.2       ]
 [0.31081081 0.1       ]
 [0.32432432 0.8       ]
 ...
 [0.24324324 0.7       ]
 [0.32432432 0.3       ]
 [0.13513514 0.4       ]]

In [33]:
# Standardization
scaler = StandardScaler()
standarizedDf = scaler.fit_transform(newDataFrame)
print(standarizedDf)

[[ 0.29368857 -1.04175968]
 [ 0.19791382 -1.38753759]
 [ 0.29368857  1.03290776]
 ...
 [-0.28095993  0.68712986]
 [ 0.29368857 -0.69598177]
 [-1.04715793 -0.35020386]]

In [35]:
# Outlier treatment

# 1. 3 Sigma Technique
data = pd.read_csv('/raw_sales.csv')
data.head()

              datesold  postcode   price propertyType  bedrooms
0  2007-02-07 00:00:00      2607  525000        house         4
1  2007-02-27 00:00:00      2906  290000        house         3
2  2007-03-07 00:00:00      2905  328000        house         3
3  2007-03-09 00:00:00      2905  380000        house         4
4  2007-03-21 00:00:00      2906  310000        house         3

In [ ]:
# Function to detect outlier on 1d datasets

def findAnomalies(data):
  anomalies = []
  randomDataStd = statistics.stdev(data)
  randomDataMean = statistics.mean(data)

  anomalyCutOff = randomDataStd * 3

  lowerLimit = randomDataMean - anomalyCutOff
  upperLimit = randomDataMean + anomalyCutOff

  for outlier in data:
    if outlier > upperLimit or outlier < lowerLimit:
      anomalies.append(outlier)
  return anomalies